version: '3.5'
services:
  mongodb:
    image: mongo:7.0
    container_name: humanstreet-mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: humanstreet
      MONGO_INITDB_ROOT_PASSWORD: humanstreet
    volumes:
      - ./.docker/mongo-init-scripts:/docker-entrypoint-initdb.d